language: node_js
node_js:
  - "stable"

branches:
  only:
    - master
    - your-branch-name # Add any additional branches you want to build on

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install -g yarn

script:
  # Uncomment the lint step if needed
  # - yarn lint
  - yarn build
  - mv build/index.html build/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Make sure the environment variable is defined correctly in Travis
  local_dir: build
  on:
    branch: master